import { Lead, Campaign, AnamneseReport } from './types';

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'Campanha de Conscientização de Saúde Bucal',
    platform: 'Meta Ads',
    status: 'Ativa',
    spend: 550.75,
    leads: 120,
  },
  {
    id: 'camp-2',
    name: 'Promoção de Vacinação Anual',
    platform: 'Meta Ads',
    status: 'Pausada',
    spend: 820.00,
    leads: 185,
  },
  {
    id: 'camp-3',
    name: 'Serviços de Estética Canina/Felina',
    platform: 'Meta Ads',
    status: 'Concluída',
    spend: 300.50,
    leads: 70,
  },
];

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    phone: '(11) 98765-4321',
    source: 'Campanha Saúde Bucal',
    status: 'Novo',
    date: '2023-10-26',
  },
  {
    id: 'lead-2',
    name: 'Roberto Santos',
    email: 'roberto.santos@email.com',
    phone: '(21) 99876-5432',
    source: 'Promoção Vacinação',
    status: 'Contatado',
    date: '2023-10-25',
  },
  {
    id: 'lead-3',
    name: 'Ana Clara',
    email: 'ana.clara@email.com',
    phone: '(31) 97654-3210',
    source: 'Serviços Estética',
    status: 'Convertido',
    date: '2023-10-24',
  },
   {
    id: 'lead-4',
    name: 'Pedro Souza',
    email: 'pedro.souza@email.com',
    phone: '(41) 96543-2109',
    source: 'Campanha Saúde Bucal',
    status: 'Novo',
    date: '2023-10-26',
  },
  {
    id: 'lead-5',
    name: 'Mariana Costa',
    email: 'mariana.costa@email.com',
    phone: '(51) 95432-1098',
    source: 'Promoção Vacinação',
    status: 'Novo',
    date: '2023-10-25',
  },
  {
    id: 'lead-6',
    name: 'João Almeida',
    email: 'joao.almeida@email.com',
    phone: '(61) 94321-0987',
    source: 'Serviços Estética',
    status: 'Contatado',
    date: '2023-10-24',
  },
   {
    id: 'lead-7',
    name: 'Camila Ribeiro',
    email: 'camila.ribeiro@email.com',
    phone: '(71) 93210-9876',
    source: 'Campanha Saúde Bucal',
    status: 'Convertido',
    date: '2023-10-26',
  },
  {
    id: 'lead-8',
    name: 'Bruno Carvalho',
    email: 'bruno.carvalho@email.com',
    phone: '(81) 92109-8765',
    source: 'Promoção Vacinação',
    status: 'Novo',
    date: '2023-10-25',
  },
  {
    id: 'lead-9',
    name: 'Luiza Martins',
    email: 'luiza.martins@email.com',
    phone: '(91) 91098-7654',
    source: 'Serviços Estética',
    status: 'Contatado',
    date: '2023-10-24',
  },
   {
    id: 'lead-10',
    name: 'Gustavo Fernandes',
    email: 'gustavo.fernandes@email.com',
    phone: '(11) 90987-6543',
    source: 'Campanha Saúde Bucal',
    status: 'Novo',
    date: '2023-10-26',
  },
  {
    id: 'lead-11',
    name: 'Carolina Pereira',
    email: 'carolina.pereira@email.com',
    phone: '(21) 99876-5432',
    source: 'Promoção Vacinação',
    status: 'Novo',
    date: '2023-10-25',
  },
  {
    id: 'lead-12',
    name: 'Daniel Rocha',
    email: 'daniel.rocha@email.com',
    phone: '(31) 98765-4321',
    source: 'Serviços Estética',
    status: 'Convertido',
    date: '2023-10-24',
  },
   {
    id: 'lead-13',
    name: 'Beatriz Gomes',
    email: 'beatriz.gomes@email.com',
    phone: '(41) 97654-3210',
    source: 'Campanha Saúde Bucal',
    status: 'Contatado',
    date: '2023-10-26',
  },
  {
    id: 'lead-14',
    name: 'Rafael Lima',
    email: 'rafael.lima@email.com',
    phone: '(51) 96543-2109',
    source: 'Promoção Vacinação',
    status: 'Novo',
    date: '2023-10-25',
  },
  {
    id: 'lead-15',
    name: 'Sofia Carvalho',
    email: 'sofia.carvalho@email.com',
    phone: '(61) 95432-1098',
    source: 'Serviços Estética',
    status: 'Novo',
    date: '2023-10-24',
  },
];

export const mockAnamneseReports: AnamneseReport[] = [
  {
    id: 'anamnese-1',
    generatedAt: '2023-10-26',
    url: '/reports/anamnese-1.pdf',
  },
  {
    id: 'anamnese-2',
    generatedAt: '2023-10-25',
    url: '/reports/anamnese-2.pdf',
  },
];
